#
# Defines environment variables.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Ensure that a non-login, non-interactive shell has a defined environment.
if [[ ( "$SHLVL" -eq 1 && ! -o LOGIN ) && -s "${ZDOTDIR:-$HOME}/.zprofile" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprofile"
fi

export TERMINAL="xterm"

export PATH="$HOME/.yarn/bin:$HOME/.config/yarn/global/node_modules/.bin:$PATH"

export GOPATH=~/projects/go
export PATH="$PATH:$GOPATH/bin"


export RUST_SRC_PATH="$HOME/rust/src"

export PATH="$HOME/.local/bin/:$PATH"

export PATH="$HOME/.emacs.d/bin/:$PATH"

export PATH="$HOME/.cabal/bin:$PATH"

export LIBVIRT_DEFAULT_URI=qemu:///system
