#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

pxa() {
  ps auxww | rg "$*" | sed "/ rg /d;/sed/d;/ps auxww/d"
}

alias killdiscord="killall Discord; killall Discord"


r() {
    tr -dc 0-9A-Za-z < /dev/urandom | dd status=none bs=1 count=${1:-13} | tee >(pbcopy) && echo
}

alias d="mktemp -d | tee /dev/stderr"
alias d.="$(mktemp -d)"

alias path="sed 's/:/\n/g' <<< $PATH"
alias l="light -S"

alias k="exa -lh"

alias chmox="chmod +x"

FZF_PATH="/usr/share/fzf"

# imperative, ew
if command -v fzf-share > /dev/null; then
  FZF_PATH=$(fzf-share)
fi

. "$FZF_PATH/key-bindings.zsh"
. "$FZF_PATH/completion.zsh"


alias ag="echo use rg"

fw() {
  fullwidth "$@" | pbcopy
}

alias pbeof="pb << 'EOF'"

alias rg="rg -P"

export NIX_AUTO_RUN=1

alias mount='mount | grep -v -E "cgmfs|tmpfs|udev|none|rpc_pipefs|binfmt|fusectl|nfsd|cgroup|tmpfs|pstore|mqueue|debugfs|hugetlbfs|cgmfs|gvfsd-fuse|securityfs|devpts|udev|sysfs|proc|vmware-vmblock" | column -t'

alias fmr='findmnt --real'

eval "$(direnv hook zsh)"
